export const osTypeEnum = {
  ios: "ios",
  android: "android",
};

// 国家信息
export const country = [
  { label: "United States", value: "US" },
//   { label: "United Kingdom", value: "GB" },
//   { label: "China", value: "CN" },
//   { label: "Canada", value: "CA" },
//   { label: "Germany", value: "DE" },
//   { label: "Japan", value: "JP" },
//   { label: "France", value: "FR" },
//   { label: "Italy", value: "IT" },
//   { label: "Spain", value: "ES" },
//   { label: "Australia", value: "AU" },
//   { label: "Albania", value: "AL" },
//   { label: "Algeria", value: "DZ" },
//   { label: "Angola", value: "AO" },
//   { label: "Antigua & Barbuda", value: "AG" },
//   { label: "Argentina", value: "AR" },
//   { label: "Armenia", value: "AM" },
//   { label: "Austria", value: "AT" },
//   { label: "Azerbaijan", value: "AZ" },
//   { label: "Bahamas", value: "BS" },
//   { label: "Bahrain", value: "BH" },
//   { label: "Belarus", value: "BY" },
//   { label: "Belgium", value: "BE" },
//   { label: "Belize", value: "BZ" },
//   { label: "Benin", value: "BJ" },
//   { label: "Bermuda", value: "BM" },
//   { label: "Bolivia", value: "BO" },
//   { label: "Bosnia & Herzegovina", value: "BA" },
//   { label: "Botswana", value: "BW" },
//   { label: "Brazil", value: "BR" },
//   { label: "British Virgin Islands", value: "VG" },
//   { label: "Bulgaria", value: "BG" },
//   { label: "Burkina Faso", value: "BF" },
//   { label: "Cambodia", value: "KH" },
//   { label: "Cameroon", value: "CM" },
//   { label: "Cape Verde", value: "CV" },
//   { label: "Cayman Islands", value: "KY" },
//   { label: "Chile", value: "CL" },
//   { label: "Colombia", value: "CO" },
//   { label: "Costa Rica", value: "CR" },
//   { label: "Côte d’Ivoire", value: "CI" },
//   { label: "Croatia", value: "HR" },
//   { label: "Cyprus", value: "CY" },
//   { label: "Czechia", value: "CZ" },
//   { label: "Denmark", value: "DK" },
//   { label: "Dominican Republic", value: "DO" },
//   { label: "Ecuador", value: "EC" },
//   { label: "Egypt", value: "EG" },
//   { label: "El Salvador", value: "SV" },
//   { label: "Estonia", value: "EE" },
//   { label: "Federated States Of Micronesia", value: "FM" },
//   { label: "Fiji", value: "FJ" },
//   { label: "Finland", value: "FI" },
//   { label: "Gabon", value: "GA" },
//   { label: "Georgia", value: "GE" },
//   { label: "Ghana", value: "GH" },
//   { label: "Greece", value: "GR" },
//   { label: "Guatemala", value: "GT" },
//   { label: "Guinea-Bissau", value: "GW" },
//   { label: "Honduras", value: "HN" },
//   { label: "Hong Kong", value: "HK" },
//   { label: "Hungary", value: "HU" },
//   { label: "Iceland", value: "IS" },
//   { label: "India", value: "IN" },
//   { label: "Indonesia", value: "ID" },
//   { label: "Iraq", value: "IQ" },
//   { label: "Ireland", value: "IE" },
//   { label: "Israel", value: "IL" },
//   { label: "Jamaica", value: "JM" },
//   { label: "Jordan", value: "JO" },
//   { label: "Kazakhstan", value: "KZ" },
//   { label: "Kenya", value: "KE" },
//   { label: "Kuwait", value: "KW" },
//   { label: "Kyrgyzstan", value: "KG" },
//   { label: "Laos", value: "LA" },
//   { label: "Latvia", value: "LV" },
//   { label: "Lebanon", value: "LB" },
//   { label: "Lithuania", value: "LT" },
//   { label: "Luxembourg", value: "LU" },
//   { label: "Macao", value: "MO" },
//   { label: "Malaysia", value: "MY" },
//   { label: "Mali", value: "ML" },
//   { label: "Malta", value: "MT" },
//   { label: "Mauritius", value: "MU" },
//   { label: "Mexico", value: "MX" },
//   { label: "Moldova", value: "MD" },
//   { label: "Morocco", value: "MA" },
//   { label: "Mozambique", value: "MZ" },
//   { label: "Myanmar", value: "MM" },
//   { label: "Namibia", value: "NA" },
//   { label: "Nepal", value: "NP" },
//   { label: "Netherlands", value: "NL" },
//   { label: "New Zealand", value: "NZ" },
//   { label: "Nicaragua", value: "NI" },
//   { label: "Niger", value: "NE" },
//   { label: "Nigeria", value: "NG" },
//   { label: "North Macedonia", value: "MK" },
//   { label: "Norway", value: "NO" },
//   { label: "Oman", value: "OM" },
//   { label: "Pakistan", value: "PK" },
//   { label: "Panama", value: "PA" },
//   { label: "Papua New Guinea", value: "PG" },
//   { label: "Paraguay", value: "PY" },
//   { label: "Peru", value: "PE" },
//   { label: "Philippines", value: "PH" },
//   { label: "Poland", value: "PL" },
//   { label: "Portugal", value: "PT" },
//   { label: "Qatar", value: "QA" },
//   { label: "Romania", value: "RO" },
//   { label: "Russia", value: "RU" },
//   { label: "Rwanda", value: "RW" },
//   { label: "Saudi Arabia", value: "SA" },
//   { label: "Senegal", value: "SN" },
//   { label: "Serbia", value: "RS" },
//   { label: "Singapore", value: "SG" },
//   { label: "Slovakia", value: "SK" },
//   { label: "Slovenia", value: "SI" },
//   { label: "Solomon Islands", value: "SB" },
//   { label: "South Africa", value: "ZA" },
//   { label: "South Korea", value: "KR" },
//   { label: "Sri Lanka", value: "LK" },
//   { label: "Sweden", value: "SE" },
//   { label: "Switzerland", value: "CH" },
//   { label: "Taiwan", value: "TW" },
//   { label: "Tajikistan", value: "TJ" },
//   { label: "Tanzania", value: "TZ" },
//   { label: "Thailand", value: "TH" },
//   { label: "Trinidad & Tobago", value: "TT" },
//   { label: "Tunisia", value: "TN" },
//   { label: "Turkey", value: "TR" },
//   { label: "Turkmenistan", value: "TM" },
//   { label: "Turks & Caicos Islands", value: "TC" },
//   { label: "Uganda", value: "UG" },
//   { label: "Ukraine", value: "UA" },
//   { label: "United Arab Emirates", value: "AE" },
//   { label: "Uruguay", value: "UY" },
//   { label: "Uzbekistan", value: "UZ" },
//   { label: "Venezuela", value: "VE" },
//   { label: "Vietnam", value: "VN" },
//   { label: "Yemen", value: "YE" },
//   { label: "Zambia", value: "ZM" },
//   { label: "Zimbabwe", value: "ZW" },
];
